# Created with YamlCreate.ps1 v2.2.0 $debug=AUSU.CRLF.5-1-19041-1682.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: Microsoft.PowerShell
PackageVersion: 7.3.101.0
Platform:
- Windows.Desktop
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- pwsh
ReleaseDate: 2022-10-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/PowerShell/PowerShell/releases/download/v7.3.0-rc.1/PowerShell-7.3.0-rc.1-win-x64.msi
  InstallerSha256: 2C304FEDCD04BD1F9040BA6DD0B6AEADA9248C7BB9B344103E1B29440793766F
  ProductCode: '{1B8F0EA3-4068-4B57-8FA3-7DD887EFD6A9}'
- Architecture: x86
  InstallerUrl: https://github.com/PowerShell/PowerShell/releases/download/v7.3.0-rc.1/PowerShell-7.3.0-rc.1-win-x86.msi
  InstallerSha256: F23DF935F22513443606B261E0EE696F3AC22A6CE77F1FF6EDE788F67E08BC60
  ProductCode: '{8EC7656F-142F-45EE-89D3-F8FD3FE6A0E7}'
- Architecture: arm
  MinimumOSVersion: 10.0.17763.0
  Platform:
  - Windows.Universal
  InstallerType: msix
  InstallerUrl: https://github.com/PowerShell/PowerShell/releases/download/v7.3.0-rc.1/PowerShell-7.3.0-rc.1-win.msixbundle
  InstallerSha256: 2A8D3B5E2F3588DF547A868EA0002362FCD9408F37AD476BA1FC791BA660E8BF
  SignatureSha256: F449FE97F331F61E773178922E3FB27D2A8987EA7AA09B4CE0C723117B5E3910
  PackageFamilyName: Microsoft.PowerShellPreview_8wekyb3d8bbwe
- Architecture: arm64
  MinimumOSVersion: 10.0.17763.0
  Platform:
  - Windows.Universal
  InstallerType: msix
  InstallerUrl: https://github.com/PowerShell/PowerShell/releases/download/v7.3.0-rc.1/PowerShell-7.3.0-rc.1-win.msixbundle
  InstallerSha256: 2A8D3B5E2F3588DF547A868EA0002362FCD9408F37AD476BA1FC791BA660E8BF
  SignatureSha256: F449FE97F331F61E773178922E3FB27D2A8987EA7AA09B4CE0C723117B5E3910
  PackageFamilyName: Microsoft.PowerShellPreview_8wekyb3d8bbwe
ManifestType: installer
ManifestVersion: 1.2.0
