# Created with YamlCreate.ps1 v2.4.1 $debug=NVS1.CRLF.7-4-4.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Microsoft.PowerShell
PackageVersion: 7.4.4.0
MinimumOSVersion: 10.0.17763.0
InstallerType: msix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- pwsh
PackageFamilyName: Microsoft.PowerShell_8wekyb3d8bbwe
ReleaseDate: 2024-07-18
Installers:
- Architecture: arm
  InstallerUrl: https://github.com/PowerShell/PowerShell/releases/download/v7.4.4/PowerShell-7.4.4-win.msixbundle
  InstallerSha256: 9C6A4AE7E94D8F39C064667CA38E79C9E24A5DF02FBFC61A9407F823011FFF15
  SignatureSha256: 0FC85E858F0BB8D5F38130BA01D3BC66D6BE273A50F73C1C1E568ADF1BE83105
ManifestType: installer
ManifestVersion: 1.6.0
