# Created with YamlCreate.ps1 v2.1.3 $debug=QUSU.7-2-5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Microsoft.PowerShell
PackageVersion: 7.0.13.0
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- pwsh
ReleaseDate: 2022-10-20
Installers:
- Architecture: x64
  MinimumOSVersion: 10.0.0.0
  Platform:
  - Windows.Desktop
  InstallerType: wix
  InstallerUrl: https://github.com/PowerShell/PowerShell/releases/download/v7.0.13/PowerShell-7.0.13-win-x64.msi
  InstallerSha256: E12CEA4C2D8F7F7C6493B5AFB44AE90B3D5C4A6CDA267F183017E6E2F8E0A57A
  ProductCode: '{CB5D5AA8-2610-4948-9F52-8BE2260D67C1}'
- Architecture: x86
  MinimumOSVersion: 10.0.0.0
  Platform:
  - Windows.Desktop
  InstallerType: wix
  InstallerUrl: https://github.com/PowerShell/PowerShell/releases/download/v7.0.13/PowerShell-7.0.13-win-x86.msi
  InstallerSha256: 88A539FE3C899E3C0920738CCBB96280D5DD318CEE34A7803E6E86632C88DDDA
  ProductCode: '{0688CCAA-0BE9-4CA6-A374-6E2562E83166}'
ManifestType: installer
ManifestVersion: 1.1.0
