# Created with YamlCreate.ps1 v2.2.1 $debug=NVS1.CRLF.7-2-7.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: Microsoft.PowerShell
PackageVersion: 7.3.0.0
InstallerType: wix
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- pwsh
ReleaseDate: 2022-11-09
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/PowerShell/PowerShell/releases/download/v7.3.0/PowerShell-7.3.0-win-x64.msi
  InstallerSha256: 5DBBFA10FD37A032414F36B9D6A8DE99E042081075DAB320C10F1F67B93E2C4E
  ProductCode: '{1460EC99-E4CB-44A3-98F9-45157F11953A}'
- Architecture: x86
  InstallerUrl: https://github.com/PowerShell/PowerShell/releases/download/v7.3.0/PowerShell-7.3.0-win-x86.msi
  InstallerSha256: 9E819F88D3CC1575EF19CC1ACF002E7D942737B9D34E8A5306410B0DF34F433C
  ProductCode: '{B9A2CD79-B8A3-42BB-BFFA-8B19004BA850}'
ManifestType: installer
ManifestVersion: 1.2.0
