# Created with YamlCreate.ps1 v2.1.3 $debug=QUSU.7-2-5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Microsoft.PowerShell
PackageVersion: 7.2.7.0
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- pwsh
ReleaseDate: 2022-10-20
Installers:
- Architecture: x64
  MinimumOSVersion: 10.0.0.0
  Platform:
  - Windows.Desktop
  InstallerType: wix
  InstallerUrl: https://github.com/PowerShell/PowerShell/releases/download/v7.2.7/PowerShell-7.2.7-win-x64.msi
  InstallerSha256: 7445F2F711759FE7167FAE2329911F9800D087265D1BA720A8801FF775AC1B31
  ProductCode: '{B5FC945E-99EE-4DB8-9AA4-B63D56D886CC}'
- Architecture: x86
  MinimumOSVersion: 10.0.0.0
  Platform:
  - Windows.Desktop
  InstallerType: wix
  InstallerUrl: https://github.com/PowerShell/PowerShell/releases/download/v7.2.7/PowerShell-7.2.7-win-x86.msi
  InstallerSha256: D9BAF2076D9F61BBB706B61542A68168FA8C870FFC41630780ACA3D1405444BD
  ProductCode: '{A8D4ED31-54E3-450F-84B4-C58694D8AC0E}'
ManifestType: installer
ManifestVersion: 1.1.0
