# Created with YamlCreate.ps1 v2.2.3 $debug=NVS1.CRLF.7-3-3.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Microsoft.PowerShell.Preview
PackageVersion: 7.4.2.0
MinimumOSVersion: 10.0.17763.0
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- pwsh
ReleaseDate: 2023-03-14
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/PowerShell/PowerShell/releases/download/v7.4.0-preview.2/PowerShell-7.4.0-preview.2-win-x64.msi
  InstallerSha256: 781AE74C9A9403409D577C1CCD699631A406DCB104B9023991731BCE60F128C3
  ProductCode: '{33E0910E-D1FB-4FB8-A72B-DF212502E4CF}'
- Architecture: x86
  InstallerUrl: https://github.com/PowerShell/PowerShell/releases/download/v7.4.0-preview.2/PowerShell-7.4.0-preview.2-win-x86.msi
  InstallerSha256: CF2DA74890738FA9845FC201FC1E657EF4C4121D2FEDBE78B9DA09B041FEF69E
  ProductCode: '{095D635E-5CDB-4FD1-AF2C-A07CC2F83DB5}'
ManifestType: installer
ManifestVersion: 1.4.0
