# Created with YamlCreate.ps1 v2.2.1 $debug=NVS1.CRLF.7-3-1.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: Microsoft.PowerShell.Preview
PackageVersion: 7.4.1.0
MinimumOSVersion: 10.0.17763.0
InstallerType: wix
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- pwsh
ReleaseDate: 2022-12-20
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/PowerShell/PowerShell/releases/download/v7.4.0-preview.1/PowerShell-7.4.0-preview.1-win-x64.msi
  InstallerSha256: C525E9D5804489183BAFCC90FC195949727593FAA780CC30D1BC01CFEFE09D0D
  ProductCode: '{3AC4078C-B562-4575-B4C9-ABDAD8F6A760}'
- Architecture: x86
  InstallerUrl: https://github.com/PowerShell/PowerShell/releases/download/v7.4.0-preview.1/PowerShell-7.4.0-preview.1-win-x86.msi
  InstallerSha256: 51EFBD58C6D7142A38D49D319EFA504DACE48B5681E98067CAFFBBF4151B84EE
  ProductCode: '{B41EB2F8-A40F-420D-98E7-1D6290F6F289}'
ManifestType: installer
ManifestVersion: 1.2.0
