# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: MicrosoftCorporation.PowerShellPreview
PackageVersion: 7.3.6.0
Installers:
- Platform:
  - Windows.Universal
  MinimumOSVersion: 10.0.17763.0
  Architecture: arm
  InstallerType: msix
  InstallerUrl: https://github.com/PowerShell/PowerShell/releases/download/v7.3.0-preview.6/PowerShell-7.3.0-preview.6-win.msixbundle
  InstallerSha256: 4555542DF654673825839170ED169C4BF01EC05CE1AB840AD5014A733FBBE4FB
  SignatureSha256: 1C08AEEEC68CC47FA28541AFF8F820C6CF444F599770FF02F0528E2B68FC75B6
  PackageFamilyName: Microsoft.PowerShellPreview_8wekyb3d8bbwe
- Platform:
  - Windows.Universal
  MinimumOSVersion: 10.0.17763.0
  Architecture: arm64
  InstallerType: msix
  InstallerUrl: https://github.com/PowerShell/PowerShell/releases/download/v7.3.0-preview.6/PowerShell-7.3.0-preview.6-win.msixbundle
  InstallerSha256: 4555542DF654673825839170ED169C4BF01EC05CE1AB840AD5014A733FBBE4FB
  SignatureSha256: 1C08AEEEC68CC47FA28541AFF8F820C6CF444F599770FF02F0528E2B68FC75B6
  PackageFamilyName: Microsoft.PowerShellPreview_8wekyb3d8bbwe
- Platform:
  - Windows.Universal
  MinimumOSVersion: 10.0.17763.0
  Architecture: x86
  InstallerType: msix
  InstallerUrl: https://github.com/PowerShell/PowerShell/releases/download/v7.3.0-preview.6/PowerShell-7.3.0-preview.6-win.msixbundle
  InstallerSha256: 4555542DF654673825839170ED169C4BF01EC05CE1AB840AD5014A733FBBE4FB
  SignatureSha256: 1C08AEEEC68CC47FA28541AFF8F820C6CF444F599770FF02F0528E2B68FC75B6
  PackageFamilyName: Microsoft.PowerShellPreview_8wekyb3d8bbwe
- Platform:
  - Windows.Universal
  MinimumOSVersion: 10.0.17763.0
  Architecture: x64
  InstallerType: msix
  InstallerUrl: https://github.com/PowerShell/PowerShell/releases/download/v7.3.0-preview.6/PowerShell-7.3.0-preview.6-win.msixbundle
  InstallerSha256: 4555542DF654673825839170ED169C4BF01EC05CE1AB840AD5014A733FBBE4FB
  SignatureSha256: 1C08AEEEC68CC47FA28541AFF8F820C6CF444F599770FF02F0528E2B68FC75B6
  PackageFamilyName: Microsoft.PowerShellPreview_8wekyb3d8bbwe
ManifestType: installer
ManifestVersion: 1.1.0

